version: '3.1'
services:
  stats-server:
    build: stats-service/
    image: "server"
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme
      - POSTGRES_USER=dmitriydemintsev
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:16.1
    container_name: explorewithme
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=dmitriydemintsev
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service/
    image: "service"
    container_name: service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmService
      - SPRING.DATASOURCE.USERNAME=dmitriydemintsev
      - SPRING.DATASOURCE.PASSWORD=root

  ewm-db:
    image: postgres:16.1
    container_name: ewmService
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmService
      - POSTGRES_USER=dmitriydemintsev
      - POSTGRES_PASSWORD=root

